routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group([
    'middleware' => ['auth', 'can:manage users'],
], function () {
    Route::resources([
        'users' => 'UsersController',
    ]);
});

Route::group([
    'middleware' => ['auth'],
], function () {
    Route::resources([
        'tasks' => 'TasksController',
        'boards' => 'BoardsController',
        'projects' => 'ProjectsController',
    ]);
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Validator;

class Project extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'tag', 'description'
    ];

    /**
     * Get the boards for the project.
     */
    public function boards() {
        return $this->hasMany('App\Board');
    }

    /**
     * Get the users for the project.
     */
    public function users() {
        return $this->belongsToMany('App\User');
    }

    /**
     * Get the lead of the project.
     */
    public function lead() {
        return $this->users()->wherePivot('lead', 1)->first();
    }

    /**
     * Get the members of the project.
     */
    public function members() {
        return $this->users()->wherePivot('lead', '<>', 1)->get();
    }

    /**
     * Get the number of tasks of the project.
     */
    public function numberOfTasks() {
        $count = 0;
        foreach($this->boards as $board) {
            $count += $board->tasks->count();
        }
        return $count;
    }

    /**
     * Validate inputs
     */
    public static function validate(array $input)
    {
        $validator = Validator::make($input, [
            'title' => 'required',
            'tag' => 'required',
            'description' => '',
            'lead' => 'required|exists:users,id'
        ]);

        return $validator;
    }
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Project;
use App\User;
use App\Label;
use Auth;

class ProjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::all();
        return view('projects.index', [
            'projects' => $projects,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all();
        $leads = User::permission('manage projects')->get();

        return view('projects.create', [
            'users' => $users,
            'leads' => $leads,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Project::validate($request->toArray());
        
        if ($validator->fails()) {
            return redirect('projects/create')
                        ->withErrors($validator)
                        ->withInput();
        }

        // create project
        $project = Project::create($request->toArray());

        // attach  members
        $project->users()->attach($request->get('members'));

        // attach the lead project marked with 1
        $project->users()->attach($request->get('lead'), ['lead' => 1]);

        return redirect('projects')->with('status', 'Project created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id, Request $request)
    {
        
        $project = Project::findOrFail($id);

        if(!($project->members()->containsStrict('id', Auth::user()->id) || $project->lead()->id == Auth::user()->id)) {
            abort(403, 'Unauthorized action.');
        }
        
        $users = User::all();
        $labels = Label::all();
        
        if($request->ajax()) {
            return json_encode($project->boards);
        }
        return view('projects.show', [
            'project' => $project,
            'users' => $users,
            'labels' => $labels,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $project = Project::findOrFail($id);
        $users = User::all();
        $leads = User::permission('manage projects')->get();
        return view('projects.edit', [
            'project' => $project,
            'users' => $users,
            'leads' => $leads,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Project::validate($request->toArray());
        
        if ($validator->fails()) {
            return redirect("projects/$id/edit")
                        ->withErrors($validator)
                        ->withInput();
        }

        // update project
        $project = Project::findOrFail($id);
        $project->update($request->toArray());

        $project->users()->detach();
        // attach members
        $project->users()->attach($request->get('members'));

        // attach the lead project marked with 1
        $project->users()->attach($request->get('lead'), ['lead' => 1]);

        return redirect('projects')->with('status', 'Project updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $project = Project::findOrFail($id);

        $project->delete();

        return redirect('projects')->with('status', 'Project deleted!');
    }
}

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="main-content p-20">
        <div class="top">
            <div class="text-left">
                <h2>Add project</h2>
            </div>
        </div>
        <div class="mt-3 d-flex">
            <form class="w-50" autocomplete="off" action="{{route('projects.store')}}" method="POST">
                @csrf
                <div class="form-group row">
                    <label for="title" class="col-sm-3 col-form-label">Title</label>
                    <div class="col-sm-9">
                        <input autocomplete="off" placeholder="Enter title" id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}">

                        @error('title')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="description" class="col-sm-3 col-form-label">Description</label>
                    <div class="col-sm-9">
                        <textarea rows="13" autocomplete="off" placeholder="Enter description" id="description" type="text" class="form-control @error('description') is-invalid @enderror" name="description">{{ old('description') }}</textarea>

                        @error('description')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="tag" class="col-sm-3 col-form-label">Tag</label>
                    <div class="col-sm-9">
                        <input autocomplete="off" placeholder="Enter tag" id="tag" type="text" class="form-control @error('tag') is-invalid @enderror" name="tag" value="{{ old('tag') }}">

                        @error('tag')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lead" class="col-sm-3 col-form-label">Project lead</label>
                    <div class="col-sm-9">
                        <select class="form-control @error('lead') is-invalid @enderror" id="lead" name="lead"value="{{ old('lead') }}">
                            <option disabled selected value="">Select an option</option>
                            @foreach($leads as $lead)
                                <option value="{{$lead->id}}">{{$lead->name}}</option>
                            @endforeach
                        </select>
                        @error('lead')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="members" class="col-sm-3 col-form-label">Members</label>
                    <div class="col-sm-9">
                        <select class="form-control js-example-basic-multiple @error('members') is-invalid @enderror" multiple="multiple" id="members" name="members[]" value="{{ old('members[]') }}">
                            @foreach($users as $user)
                                <option value="{{$user->id}}">{{$user->name}}</option>
                            @endforeach
                        </select>
                        @error('members')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row mb-0">
                    <div class="col-md-2 offset-md-10 text-right">
                        <button type="submit" class="btn btn-simple">
                            Create
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="main-content p-20">
        <div class="top">
            <div class="text-left">
                <h2>Edit project</h2>
            </div>
        </div>
        <div class="mt-3 d-flex">
            <form class="w-50" autocomplete="off" action="{{route('projects.update', $project->id)}}" method="POST">
                @csrf
                <input name="_method" type="hidden" value="PUT">
                <div class="form-group row">
                    <label for="title" class="col-sm-3 col-form-label">Title</label>
                    <div class="col-sm-9">
                        <input autocomplete="off" placeholder="Enter title" id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ $project->title }}">

                        @error('title')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="description" class="col-sm-3 col-form-label">Description</label>
                    <div class="col-sm-9">
                        <textarea rows="13" autocomplete="off" placeholder="Enter description" id="description" type="text" class="form-control @error('description') is-invalid @enderror" name="description">{{ $project->description }}</textarea>

                        @error('description')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="tag" class="col-sm-3 col-form-label">Tag</label>
                    <div class="col-sm-9">
                        <input autocomplete="off" placeholder="Enter tag" id="tag" type="text" class="form-control @error('tag') is-invalid @enderror" name="tag" value="{{ $project->tag }}">

                        @error('tag')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="lead" class="col-sm-3 col-form-label">Project lead</label>
                    <div class="col-sm-9">
                        <select class="form-control @error('lead') is-invalid @enderror" id="lead" name="lead"value="{{ old('lead') }}">
                            <option diabled value="">Select an option</option>
                            @foreach($leads as $lead)
                                <option value="{{$lead->id}}" @if($lead->id == $project->lead()->id) selected="selected" @endif>{{$lead->name}}</option>
                            @endforeach
                        </select>
                        @error('lead')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="members" class="col-sm-3 col-form-label">Members</label>
                    <div class="col-sm-9">
                        <select class="form-control js-example-basic-multiple @error('members') is-invalid @enderror" multiple="multiple" id="members" name="members[]" value="{{ old('members[]') }}">
                            @foreach($users as $user)
                                <option value="{{$user->id}}" @if($project->members()->containsStrict('id', $user->id)) selected="selected" @endif>{{$user->name}}</option>
                            @endforeach
                        </select>
                        @error('members')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row mb-0">
                    <div class="col-md-2 offset-md-10 text-right">
                        <button type="submit" class="btn btn-simple">
                            Update
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="main-content p-20">
        <div class="top">
            <div class="text-left d-inline-flex">
                <h2>Projects</h2>
            </div>
            @can('manage projects')
                <div class="pull-right">
                    <a href="{{route('projects.create')}}" class="btn btn-simple"><i class="fa fa-plus"></i> Add project</a>
                </div>
            @endcan
        </div>
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        <div class="mt-3">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Tag</th>
                        <th>Project lead</th>
                        <th>Contributors</th>
                        <th>Tasks</th>
                        @can('manage projects')
                            <th>Actions</th>
                        @endcan
                    </tr>
                </thead>
                <tbody>
                    @foreach($projects as $project) 
                        @if($project->members()->containsStrict('id', Auth::user()->id) || $project->lead()->id == Auth::user()->id)
                            <tr>
                                <td>
                                    <a href="{{route('projects.show', $project->id)}}">{{$project->title}}<a>
                                </td>
                                <td><span class="badge badge-simple text-uppercase">{{$project->tag}}</span></td>
                                <td>{{$project->lead()->name}}</td>
                                <td>
                                    @foreach($project->members() as $member)
                                        <a href="{{route('users.show', $member->id)}}"><small>{{$member->name}}</small></a><br>
                                    @endforeach
                                </td>
                                <td>{{$project->numberOfTasks()}}</td>
                                @can('manage projects')
                                    <td class="d-flex">
                                        <a class="btn btn-sm btn-simple mr-1" href="{{route('projects.edit', $project->id)}}">Edit</a>
                                        <form action="{{route('projects.destroy', $project->id)}}" method="POST">
                                            @csrf
                                            <input name="_method" type="hidden" value="DELETE">
                                            <button type="submit" class="btn btn-sm btn-simple" onclick="return confirm('Are you sure you want to delete the project?')">Delete</a>
                                        </form>
                                    </td>
                                @endcan
                            </tr>
                        @endif
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection