routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group([
    'middleware' => ['auth', 'can:manage users'],
], function () {
    Route::resources([
        'users' => 'UsersController',
    ]);
});

Route::group([
    'middleware' => ['auth'],
], function () {
    Route::resources([
        'tasks' => 'TasksController',
        'boards' => 'BoardsController',
        'projects' => 'ProjectsController',
    ]);
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Permission\Traits\HasPermissions;
use Illuminate\Support\Facades\Validator;


class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    use HasPermissions;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
    * Get the projects for the users.
    */
    public function projects() {
        return $this->belongsToMany('App\Project');
    }

    /**
    * Get the tasks for the users.
    */
    public function tasks() {
        return $this->hasMany('App\User');
    }

    /**
     * Get the tasks created by the user
     */

    public function createdTasks() {
        return $this->hasMany('App\User', 'created_by_user_id', 'user_id');
    }

    /**
     * Validate inputs
     */
    public static function validate(array $input)
    {
        $validator = Validator::make($input, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required',
        ]);

        return $validator;
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Project;
use App\Task;
use Spatie\Permission\Models\Permission;
use Illuminate\Support\Facades\Validator;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('name', 'asc')->get();
        
        return view('users.index', [
            'users' => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::all();
        $projects = Project::all();
        return view('users.create', [
            'permissions' => $permissions,
            'projects' => $projects,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = User::validate($request->toArray());
        
        if ($validator->fails()) {
            return redirect("users/create")
                        ->withErrors($validator)
                        ->withInput();
        }

        // create user
        $user = User::create($request->toArray());

        $user->projects()->attach($request->get('projects'), ['lead' => 0]);

        $user->syncPermissions($request->get('permissions'));

        return redirect("users")->with('status', 'User created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        $permissions = $user->getAllPermissions();
        $tasks = Task::where('user_id', $id)
            ->join('labels', 'labels.id', '=', 'tasks.label_id')
            ->orderBy('completed', 'asc')
            ->orderBy('due_date', 'asc')
            ->orderBy('labels.priority', 'asc')
            ->select('tasks.*') //see PS:
            ->get();
        return view('users.show', [
            'user' => $user,
            'permissions' => $permissions,
            'tasks' => $tasks,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $permissions = Permission::all();
        $projects = Project::all();

        return view('users.edit', [
            'user' => $user,
            'permissions' => $permissions,
            'projects' => $projects,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);

        $validator = Validator::make($request->toArray(), [
            'name' => 'required',
            'email' => 'required|email|unique:users,email,'.$user->id,
            'password' => 'required',
        ]);
        
        if ($validator->fails()) {
            return redirect("users/$id/edit")
                        ->withErrors($validator)
                        ->withInput();
        }

        // update user
        $user->update($request->toArray());

        $user->projects()->detach();

        // attach member
        $user->projects()->wherePivot('lead', 0)->sync($request->get('projects'));

        $user->syncPermissions($request->get('permissions'));

        return redirect('users')->with('status', 'User updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);

        $user->delete();

        return redirect('users')->with('status', 'User deleted!');
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="main-content p-20">
        <div class="top">
            <div class="text-left">
                <h2>Add user</h2>
            </div>
        </div>
        <div class="mt-3 d-flex">
            <form class="w-50" autocomplete="off" action="{{route('users.store')}}" method="POST">
                @csrf
                <div class="form-group row">
                    <label for="name" class="col-sm-3 col-form-label">Name</label>
                    <div class="col-sm-9">
                        <input autocomplete="off" placeholder="Enter name" id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}">

                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="email" class="col-sm-3 col-form-label">Email</label>
                    <div class="col-sm-9">
                        <input autocomplete="off" placeholder="Enter email" id="email" type="text" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}">

                        @error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="password" class="col-sm-3 col-form-label">Password</label>
                    <div class="col-sm-9">
                        <input autocomplete="off" type="password" class="form-control @error('password') is-invalid @enderror" id="password" placeholder="Password" name="password" value="{{ old('password') }}">
                       
                        @error('password')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="permissions" class="col-sm-3 col-form-label">Permissions</label>
                    <div class="col-sm-9">
                        <select class="form-control js-example-basic-multiple @error('permissions') is-invalid @enderror" multiple="multiple" id="permissions" name="permissions[]" value="{{ old('permissions[]') }}">
                            @foreach($permissions as $permission)
                                <option value="{{$permission->id}}">{{$permission->name}}</option>
                            @endforeach
                        </select>
                        @error('permissions')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="projects" class="col-sm-3 col-form-label">Projects</label>
                    <div class="col-sm-9">
                        <select class="form-control js-example-basic-multiple @error('projects') is-invalid @enderror" multiple="multiple" id="projects" name="projects[]" value="{{ old('projects[]') }}">
                            @foreach($projects as $project)
                                <option value="{{$project->id}}">{{$project->title}}</option>
                            @endforeach
                        </select>
                        @error('projects')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row mb-0">
                    <div class="col-md-2 offset-md-10 text-right">
                        <button type="submit" class="btn btn-simple">
                            Create
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="main-content p-20">
        <div class="top">
            <div class="text-left">
                <h2>Add user</h2>
            </div>
        </div>
        <div class="mt-3 d-flex">
            <form class="w-50" autocomplete="off" action="{{route('users.update', $user->id)}}" method="POST">
                @csrf
                <input name="_method" type="hidden" value="PUT">
                <div class="form-group row">
                    <label for="name" class="col-sm-3 col-form-label">Name</label>
                    <div class="col-sm-9">
                        <input autocomplete="off" placeholder="Enter name" id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name }}">

                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="email" class="col-sm-3 col-form-label">Email</label>
                    <div class="col-sm-9">
                        <input autocomplete="off" placeholder="Enter email" id="email" type="text" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}">

                        @error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="password" class="col-sm-3 col-form-label">Password</label>
                    <div class="col-sm-9">
                        <input autocomplete="off" type="password" class="form-control @error('password') is-invalid @enderror" id="password" placeholder="Password" name="password" value="{{ $user->password }}">
                       
                        @error('password')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="permissions" class="col-sm-3 col-form-label">Permissions</label>
                    <div class="col-sm-9">
                        <select class="form-control js-example-basic-multiple @error('permissions') is-invalid @enderror" multiple="multiple" id="permissions" name="permissions[]" value="{{ old('permissions[]') }}">
                            @foreach($permissions as $permission)
                                <option value="{{$permission->id}}" @if($user->getAllPermissions()->containsStrict('id', $permission->id)) selected="selected" @endif>{{$permission->name}}</option>
                            @endforeach
                        </select>
                        @error('permissions')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="projects" class="col-sm-3 col-form-label">Projects</label>
                    <div class="col-sm-9">
                        <select class="form-control js-example-basic-multiple @error('projects') is-invalid @enderror" multiple="multiple" id="projects" name="projects[]" value="{{ old('projects[]') }}">
                            @foreach($projects as $project)
                                <option value="{{$project->id}}" @if($project->users->containsStrict('id', $user->id)) selected="selected" @endif>{{$project->title}}</option>
                            @endforeach
                        </select>
                        @error('projects')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row mb-0">
                    <div class="col-md-2 offset-md-10 text-right">
                        <button type="submit" class="btn btn-simple">
                            Update
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="main-content p-20">
        <div class="top">
            <div class="text-left d-inline-flex">
                <h2>Users</h2>
            </div>
            <div class="pull-right">
                <a href="{{route('users.create')}}" class="btn btn-simple"><i class="fa fa-plus"></i> Add user</a>
            </div>
        </div>
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        <div class="mt-3">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>E-mail</th>
                        <th>Projects</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $user) 
                        <tr>
                            <td>
                                <a href="{{route('users.show', $user->id)}}">{{$user->name}}<a>
                            </td>
                            <td>{{$user->email}}</td>
                            <td>
                                @foreach($user->projects as $project)
                                    <a href="{{route('projects.show', $project->id)}}"><small>{{$project->title}}</small></a><br>
                                @endforeach
                            </td>
                            <td class="d-flex">
                                <a class="btn btn-sm btn-simple mr-1" href="{{route('users.edit', $user->id)}}">Edit</a>
                                <form action="{{route('users.destroy', $user->id)}}" method="POST">
                                    @csrf
                                    <input name="_method" type="hidden" value="DELETE">
                                    <button type="submit" class="btn btn-sm btn-simple" onclick="return confirm('Are you sure you want to delete the project?')">Delete</a>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="main-content p-20">
        <div class="top">
            <div class="pull-left">
                <h2>{{$user->name}}</h2>
                <small>{{$user->email}}</small>
            </div>

            <div class="pull-right">
                <h5>Permissions</h2>
                @foreach($permissions as $permission) 
                    <small>{{$permission->name}}, </small>
                @endforeach
            </div>
        </div>
        <div class="mt-10">
            <table class="table-striped">
                <thead>
                    <tr>
                        <th>Priority</th>
                        <th>Due date</th>
                        <th>Completed</th>
                        <th>Tag</th>
                        <th>Title</th>
                        <th>Assigned to</th>
                        <th>Project</th>
                        @can('manage own tasks')
                            <th>Actions</th>
                        @endcan
                    </tr>
                </thead>
                <tbody>
                    @foreach($tasks as $task) 
                        <tr>
                            <td>
                                @if(is_null($task->completed)) 
                                    <i class="fa fa-times text-danger font-20 vertical-bottom"></i> 
                                @else
                                    <i class="fa fa-check-square text-success font-20 vertical-bottom"></i> 
                                @endif
                                <i class="vertical-bottom font-weight-bolder font-20 {{$task->label->icon}}" style="color: {{$task->label->color}}"></i> {{$task->label->title}}
                            </td>
                            <td>{{$task->due_date}}</td>
                            <td>{{$task->completed}}</td>
                            <td><span class="badge badge-simple text-uppercase">{{$task->board->project->tag}}-{{$task->id}}</span></td>
                            <td>{{$task->title}}</td>
                            <td>{{$task->user->name}}</td>
                            <td>{{$task->board->project->title}}</td>
                            @can('manage own tasks')
                                <td class="d-flex">
                                    <a class="btn btn-sm btn-simple mr-1" href="{{route('tasks.edit', $task->id)}}">Edit</a>
                                    @if($task->created_by_user_id == Auth::id())
                                        <form action="{{route('tasks.destroy', $task->id)}}" method="POST">
                                            @csrf
                                            <input name="_method" type="hidden" value="DELETE">
                                            <button type="submit" class="btn btn-sm btn-simple" onclick="return confirm('Are you sure you want to delete the task?')">Delete</a>
                                        </form>
                                    @endif
                                </td>
                            @endcan
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection