routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group([
    'middleware' => ['auth', 'can:manage users'],
], function () {
    Route::resources([
        'users' => 'UsersController',
    ]);
});

Route::group([
    'middleware' => ['auth'],
], function () {
    Route::resources([
        'tasks' => 'TasksController',
        'boards' => 'BoardsController',
        'projects' => 'ProjectsController',
    ]);
});

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Validator;

class Task extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'due_date', 'completed', 'label_id', 'user_id', 'board_id', 'created_by_user_id',
    ];

    /**
     * Get the board of the task.
     */
    public function board() {
        return $this->belongsTo('App\Board');
    }

    /**
     * Get the user of the task.
     */
    public function user() {
        return $this->belongsTo('App\User');
    }

    /**
     * Get the user who create the task.
     */
    public function createdBy() {
        return $this->belongsTo('App\User', 'created_by_user_id');
    }

    /**
     * Get the label of the task.
     */
    public function label() {
        return $this->belongsTo('App\Label');
    }

    /**
     * Validate inputs
     */
    public static function validate(array $input)
    {
        $validator = Validator::make($input, [
            'title' => 'required',
            'due_date' => 'required|date',
            'label_id' => 'required|exists:labels,id', 
            'user_id' => 'required|exists:users,id',
            'board_id' => 'required|exists:boards,id',
        ]);

        return $validator;
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Task;
use App\Project;
use App\Label;
use App\User;
use Auth;

class TasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();

        if($user->hasPermissionTo('manage tasks')) {
            $tasks = Task::join('labels', 'labels.id', '=', 'tasks.label_id')
            ->orderBy('completed', 'asc')
            ->orderBy('due_date', 'asc')
            ->orderBy('labels.priority', 'asc')
            ->select('tasks.*') //see PS:
            ->get();
        } else {
            $tasks = Task::join('labels', 'labels.id', '=', 'tasks.label_id')
            ->where('tasks.user_id', $user->id)
            ->orderBy('completed', 'asc')
            ->orderBy('due_date', 'asc')
            ->orderBy('labels.priority', 'asc')
            ->select('tasks.*') //see PS:
            ->get();
        }
       
        return view('tasks.index', [
            'tasks' => $tasks,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $projects = Project::all();
        $labels = Label::all();
        $users = User::all();
        return view('tasks.create', [
            'projects' => $projects,
            'labels' => $labels,
            'users' => $users,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Task::validate($request->toArray());
        $project_id = $request->get('project_id');
        if ($validator->fails() && $request->get('task')) {
            return redirect("tasks")
                        ->withErrors($validator);
        } elseif($validator->fails()) {
            return redirect("projects/$project_id")
                        ->with('fail_task', 1)
                        ->withErrors($validator);
        }
        $data = $request->toArray();
        $data['created_by_user_id'] = Auth::id();
        // create task
        $task = Task::create($data);

        if($request->get('task')) {
            return redirect("tasks")->with('status', 'Task created!');
        }
        return redirect("projects/$project_id")->with('status', 'Task created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $task = Task::findOrFail($id);
        $task->setAttribute('url', route('tasks.update', $id));
        $task->setAttribute('project_id', $task->board->project->id);
        return $task;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $task = Task::findOrFail($id);
        $project = Project::findOrFail($task->board->project->id);
        $labels = Label::all();
        $users = User::all();
        return view('tasks.edit', [
            'project' => $project,
            'labels' => $labels,
            'users' => $users,
            'task' => $task,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Task::validate($request->toArray());
        $project_id = $request->get('project_id');

        if ($validator->fails() && $request->get('task')) {
            return redirect("tasks/$id/edit")
                        ->withErrors($validator);
        } elseif($validator->fails()) {
            return redirect("projects/$project_id")
                        ->with('fail_task', 1)
                        ->withErrors($validator);
        }

        // update task
        $task = Task::findOrFail($id);

        $data = $request->toArray();

        $task->update($data);

        if($request->get('task')) {
            return redirect("tasks")->with('status', 'Task updated!');
        }

        return redirect("projects/$project_id")->with('status', 'Task updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $task = Task::findOrFail($id);

        $task->delete();

        return redirect('tasks')->with('status', 'Task deleted!');
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="main-content p-20">
        <div class="top">
            <div class="text-left d-inline-flex">
                <h2>Tasks</h2>
            </div>
            @canany(['manage tasks', 'add own task'])
                <div class="pull-right">
                    <a href="{{route('tasks.create')}}" class="btn btn-simple"><i class="fa fa-plus"></i> Add task</a>
                </div>
            @endcan
        </div>
        <div class="mt-3">
            <form method="post" action="{{route('tasks.store')}}">
                @csrf
                <input type="hidden" value="1" name="task">
                <div class="form-group row">
                    <label for="project_id" class="col-sm-3 col-form-label">Projects</label>
                    <div class="col-sm-9">
                        <select class="form-control @error('project_id') is-invalid @enderror" id="project_id" name="project_id"value="{{ old('project_id') }}">
                            <option disabled selected value="">Select an option</option>
                            @foreach($projects as $project)
                                @if($project->members()->containsStrict('id', Auth::user()->id) || $project->lead()->id == Auth::user()->id)
                                    <option value="{{$project->id}}">{{$project->title}}</option>
                                @endif
                            @endforeach
                        </select>
                        @error('project_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <label for="title" class="col-sm-3 col-form-label">Title</label>
                    <div class="col-sm-9">
                        <input autocomplete="off" placeholder="Enter title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}">

                        @error('title')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="label_id" class="col-sm-3 col-form-label">Priority</label>
                    <div class="col-sm-9">
                        <select class="form-control @error('label_id') is-invalid @enderror" name="label_id"value="{{ old('label_id') }}">
                            <option disabled selected value="">Select an option</option>
                            @foreach($labels as $label)
                                <option value="{{$label->id}}">{{$label->title}}</option>
                            @endforeach
                        </select>
                        @error('label_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="due_date" class="col-sm-3 col-form-label">Due date</label>
                    <div class="col-sm-9">
                        <input autocomplete="off" placeholder="Enter date" type="date" class="form-control @error('due_date') is-invalid @enderror" name="due_date" value="{{ old('due_date') }}">

                        @error('due_date')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                @can('manage tasks')
                    <div class="form-group row">
                        <label for="user_id" class="col-sm-3 col-form-label">Users</label>
                        <div class="col-sm-9">
                            <select class="form-control @error('user_id') is-invalid @enderror" name="user_id"value="{{ old('user_id') }}">
                                <option disabled selected value="">Select an option</option>
                                @foreach($users as $user)
                                    <option value="{{$user->id}}">{{$user->name}}</option>
                                @endforeach
                            </select>
                            @error('user_id')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                @else
                    <input type="hidden" value="{{Auth::id()}}" name="user_id">
                @endcan

                <div class="form-group row">
                    <label for="board_id" class="col-sm-3 col-form-label">Board</label>
                    <div class="col-sm-9">
                        <select class="form-control @error('board_id') is-invalid @enderror" id="board_id" name="board_id"value="{{ old('board_id') }}">
                            <option disabled selected value="">Select an option</option>
                            
                        </select>
                        @error('board_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group mb-0">
                    <div class="pull-right">
                        <button type="submit" class="btn btn-simple">
                            Create
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    
<script>

    $(document).ready(function(){
        $('#project_id').change(function(){
    
            // projct  id
            var id = $(this).val();
    
            // Empty the dropdown
            $('#board_id').find('option').not(':first').remove();
    
            // AJAX request 
            $.ajax({
                url: '../projects/'+id,
                type: 'get',
                dataType: 'json',
                success: function(response){
                    var len = 0;
                    if(response != null){
                        len = response.length;
                    }
                    if(len > 0){
                        // Read data and create <option >
                        for(var i=0; i<len; i++){
    
                            var id = response[i].id;
                            var title = response[i].title;
                            var option = "<option value='"+id+"'>"+title+"</option>"; 
    
                            $("#board_id").append(option); 
                        }
                    }
                }
            });
        });
    });
    
    </script>
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="main-content p-20">
        <div class="top">
            <div class="text-left d-inline-flex">
                <h2>Tasks</h2>
            </div>
            @canany(['manage tasks', 'add own task'])
                <div class="pull-right">
                    <a href="{{route('tasks.create')}}" class="btn btn-simple"><i class="fa fa-plus"></i> Add task</a>
                </div>
            @endcan
        </div>
        <div class="mt-3">
            <form method="post" class="form-update" action="{{route('tasks.update', $task->id)}}">
                @csrf
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" value="{{$project->id}}" name="project_id">
                <input type="hidden" value="1" name="task">

                <div class="form-group row">
                    <label for="title" class="col-sm-3 col-form-label">Title</label>
                    <div class="col-sm-9">
                        <input autocomplete="off" placeholder="Enter title" id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ $task->title }}">

                        @error('title')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="label_id" class="col-sm-3 col-form-label">Priority</label>
                    <div class="col-sm-9">
                        <select class="form-control @error('label_id') is-invalid @enderror" id="label_id" name="label_id">
                            <option disabled selected value="">Select an option</option>
                            @foreach($labels as $label)
                                <option value="{{$label->id}}" @if($task->label_id == $label->id) selected="selected" @endif>{{$label->title}}</option>
                            @endforeach
                        </select>
                        @error('label_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="due_date" class="col-sm-3 col-form-label">Due date</label>
                    <div class="col-sm-9">
                        <input autocomplete="off" placeholder="Enter date" id="due_date" type="date" class="form-control @error('due_date') is-invalid @enderror" name="due_date" value="{{ $task->due_date }}">

                        @error('due_date')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                @can('manage tasks')
                    <div class="form-group row">
                        <label for="user_id" class="col-sm-3 col-form-label">Users</label>
                        <div class="col-sm-9">
                            <select class="form-control @error('user_id') is-invalid @enderror" id="user_id" name="user_id">
                                <option disabled selected value="">Select an option</option>
                                @foreach($users as $user)
                                    <option value="{{$user->id}}" @if($task->user_id == $user->id) selected="selected" @endif>{{$user->name}}</option>
                                @endforeach
                            </select>
                            @error('user_id')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                @else
                    <input type="hidden" value="{{Auth::id()}}" name="user_id">
                @endcan

                <div class="form-group row">
                    <label for="board_id" class="col-sm-3 col-form-label">Board</label>
                    <div class="col-sm-9">
                        <select class="form-control @error('board_id') is-invalid @enderror" id="board_id" name="board_id"value="{{ old('board_id') }}">
                            <option disabled selected value="">Select an option</option>
                            @foreach($project->boards as $board)
                                <option value="{{$board->id}}" @if($task->board_id == $board->id) selected="selected" @endif>{{$board->title}}</option>
                            @endforeach
                        </select>
                        @error('board_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="completed" class="col-sm-3 col-form-label">Completed</label>
                    <div class="col-sm-9">
                        <input autocomplete="off" placeholder="Enter date" id="completed" type="date" class="form-control @error('completed') is-invalid @enderror" name="completed" value="{{ $task->completed }}">

                        @error('completed')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group mb-0">
                    <div class="pull-right">
                        <button type="submit" class="btn btn-simple">
                            Update
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    
<script>

    $(document).ready(function(){
        $('#project_id').change(function(){
    
            // projct  id
            var id = $(this).val();
    
            // Empty the dropdown
            $('#board_id').find('option').not(':first').remove();
    
            // AJAX request 
            $.ajax({
                url: '../projects/'+id,
                type: 'get',
                dataType: 'json',
                success: function(response){
                    var len = 0;
                    if(response != null){
                        len = response.length;
                    }
                    if(len > 0){
                        // Read data and create <option >
                        for(var i=0; i<len; i++){
    
                            var id = response[i].id;
                            var title = response[i].title;
                            var option = "<option value='"+id+"'>"+title+"</option>"; 
    
                            $("#board_id").append(option); 
                        }
                    }
                }
            });
        });
    });
    
    </script>
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="main-content p-20">
        <div class="top">
            <div class="text-left d-inline-flex">
                <h2>Tasks</h2>
            </div>
            @canany(['manage tasks', 'add own task'])
                <div class="pull-right">
                    <a href="{{route('tasks.create')}}" class="btn btn-simple"><i class="fa fa-plus"></i> Add task</a>
                </div>
            @endcan
        </div>
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        <div class="mt-3">
            <table class="table-striped">
                <thead>
                    <tr>
                        <th>Priority</th>
                        <th>Due date</th>
                        <th>Completed</th>
                        <th>Tag</th>
                        <th>Title</th>
                        <th>Assigned to</th>
                        <th>Project</th>
                        @can('manage own tasks')
                            <th>Actions</th>
                        @endcan
                    </tr>
                </thead>
                <tbody>
                    @foreach($tasks as $task) 
                        <tr>
                            <td>
                                @if(is_null($task->completed)) 
                                    <i class="fa fa-times text-danger font-20 vertical-bottom"></i> 
                                @else
                                    <i class="fa fa-check-square text-success font-20 vertical-bottom"></i> 
                                @endif
                                <i class="vertical-bottom font-weight-bolder font-20 {{$task->label->icon}}" style="color: {{$task->label->color}}"></i> {{$task->label->title}}
                            </td>
                            <td>{{$task->due_date}}</td>
                            <td>{{$task->completed}}</td>
                            <td><span class="badge badge-simple text-uppercase">{{$task->board->project->tag}}-{{$task->id}}</span></td>
                            <td>{{$task->title}}</td>
                            <td>{{$task->user->name}}</td>
                            <td>{{$task->board->project->title}}</td>
                            @can('manage own tasks')
                                <td class="d-flex">
                                    <a class="btn btn-sm btn-simple mr-1" href="{{route('tasks.edit', $task->id)}}">Edit</a>
                                    @if($task->created_by_user_id == Auth::id() || Auth::user()->hasRole('admin'))
                                        <form action="{{route('tasks.destroy', $task->id)}}" method="POST">
                                            @csrf
                                            <input name="_method" type="hidden" value="DELETE">
                                            <button type="submit" class="btn btn-sm btn-simple" onclick="return confirm('Are you sure you want to delete the task?')">Delete</a>
                                        </form>
                                    @endif
                                </td>
                            @endcan
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection